name: Deploy Image to Docker Hub
on: 
  push:
    tags:
      - "release*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker hub login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USER --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-to-typescript:$(date +%s)
    - name: Push to docker hub
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
      run: docker push $DOCKERHUB_USER/go-to-typescript
